# Generated by Django 3.0.2 on 2020-02-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='current_action',
            field=models.CharField(default='defend', max_length=255),
            preserve_default=False,
        ),
    ]
