# Generated by Django 3.0.2 on 2020-02-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='identifier',
            field=models.IntegerField(max_length=255),
        ),
    ]
