# Generated by Django 3.0.2 on 2020-02-01 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='soldier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.Soldier'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='command',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='game.Command'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='time_in_minutes',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('date', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.Profile')),
            ],
        ),
    ]
