# Generated by Django 3.0.2 on 2020-02-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200201_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='profile',
        ),
        migrations.AddField(
            model_name='message',
            name='identifier',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
