# Generated by Django 3.0.2 on 2020-02-01 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200201_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='game.Field'),
        ),
    ]
